version: "3.8"
services:
  database:
    image: 'postgres:14-alpine'
    container_name: postgres14
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_server
  # The `volumes` tag allows us to share a folder with our container.
  # Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
    volumes:
  # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
  # It means that every time the repository is modifying the data inside
  # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
  # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      - /home/prakhar/Desktop/db-data:/var/lib/postgresql/test
  cache:
    image: 'redis:7.0-alpine'
    container_name: redis-7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - /data