// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID         int64     `json:"id"`
	OwnerEmail string    `json:"owner_email"`
	Balance    int64     `json:"balance"`
	Currency   string    `json:"currency"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type AccountTransactionsEntry struct {
	ID            int64         `json:"id"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	AccountID     sql.NullInt64 `json:"account_id"`
	OtherAccount  sql.NullInt64 `json:"other_account"`
	// must be positive
	Amount    int64          `json:"amount"`
	Type      sql.NullString `json:"type"`
	CreatedAt time.Time      `json:"created_at"`
}

type Transaction struct {
	ID            int64         `json:"id"`
	TransactionID sql.NullInt64 `json:"transaction_id"`
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	// can be negative depending on debit or credit
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
