# cluster.yaml
# A cluster with two managed nodegroup
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kuber
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 80
