// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountStatementEntry(ctx context.Context, arg CreateAccountStatementEntryParams) (AccountTransactionsEntry, error)
	CreateTransferRecord(ctx context.Context, arg CreateTransferRecordParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetAccountByOwnerEmail(ctx context.Context, ownerEmail string) (Account, error)
	GetBalanceByAccountId(ctx context.Context, id int64) (int64, error)
	GetBalanceByOwnerEmail(ctx context.Context, ownerEmail string) (int64, error)
	GetTransaction(ctx context.Context, uid uuid.UUID) (Transaction, error)
	GetTransactionsList(ctx context.Context) ([]Transaction, error)
	GetUserDetails(ctx context.Context, userEmail string) (GetUserDetailsRow, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccountBalanceById(ctx context.Context, arg UpdateAccountBalanceByIdParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
